db:
  path: ./.silent-pay-indexer/db/database.sqlite
  synchronize: true
app:
  port: 3000
  network: regtest
  requestRetry:
    delay: 500
    count: 1
providerType: BITCOIN_CORE_RPC
bitcoinCore:
  protocol: http
  rpcHost: 127.0.0.1
  rpcPass: password
  rpcUser: polaruser
  rpcPort: 18443
